In [ ]:
#Summary for numpy, pandas usage in python

# numpy usage

## construct np data

In [58]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0,2,20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [7]:
np.array([0,2,5,6,8])

array([0, 2, 5, 6, 8])

In [12]:
np.random.randint(10,size=(2,3))

array([[7, 9, 1],
       [7, 3, 7]])

In [44]:
s=np.random.normal(0,1,size=(10,100))

In [45]:
s_mean_square=s.mean(axis=0)**2

In [46]:
s_std=s.std(axis=0)*10/9

In [47]:
(s_mean_square/s_std).mean()

0.11004755632605613

In [48]:
9/7/10

0.1285714285714286

## index numpy

In [49]:
a=np.array([0,2,5,6,9])

In [50]:
a[1]

2

In [51]:
a[0:3]

array([0, 2, 5])

In [52]:
a[-1]

9

In [55]:
a[-2:-1]

array([6])

In [56]:
a[::2]

array([0, 5, 9])

In [57]:
a[::-1]

array([9, 6, 5, 2, 0])

In [59]:
s[0,1]

-2.2389545718788813

In [60]:
s[1:3,2:4]

array([[-1.9003874 , -1.21967461],
       [-0.22528338,  0.29502568]])

In [61]:
s[1,:]

array([ 0.81192976,  0.69150002, -1.9003874 , -1.21967461,  1.51717907,
       -1.00492202,  0.16675044,  0.67881463, -0.73809753, -0.10446252,
       -0.63726253,  0.17486457, -0.09710027, -1.71629881, -0.02261325,
       -1.7542553 ,  0.67489189,  0.08105935, -0.65196046, -2.05719343,
       -1.43923651,  0.32777288, -1.47777341, -0.52141085, -0.5191718 ,
       -1.06650498,  0.12346097,  0.77436425, -1.61995782,  0.0151088 ,
        0.64635395, -0.98078627, -0.85875464, -0.53678008,  0.74984269,
        0.4482447 , -0.18454625,  1.49118591,  1.90653489,  1.7738534 ,
       -0.87220266, -0.65721126,  0.83497317,  1.06503574, -0.73951491,
        1.30743763, -0.75559763, -0.94266403,  0.70061484,  1.65807085,
        1.47744223,  0.51240777, -0.23439146,  0.82592286,  0.2678051 ,
       -0.05397431, -0.14612757,  0.1353896 ,  0.40292116, -0.42782156,
        0.99923594,  0.56703379, -1.91424269, -1.36177309,  1.52484191,
       -1.10322409,  1.34609812,  0.12183728,  0.39047226, -0.49

## calculation and manipulation

In [62]:
a+a

array([ 0,  4, 10, 12, 18])

In [63]:
a+5

array([ 5,  7, 10, 11, 14])

In [64]:
a.mean()

4.4

In [65]:
a.std()

3.1368774282716245

In [67]:
np.hstack((a,a))

array([0, 2, 5, 6, 9, 0, 2, 5, 6, 9])

In [68]:
np.vstack((a,a))

array([[0, 2, 5, 6, 9],
       [0, 2, 5, 6, 9]])

In [72]:
np.concatenate((a,a),axis=0)

array([0, 2, 5, 6, 9, 0, 2, 5, 6, 9])

# Pandas usage

## series

In [74]:
import pandas as pd

### construct series

In [78]:
q=pd.Series([1,3,4],index=['a','d','e'])

In [77]:
a={'a':1,'d':3,'e':4}
pd.Series(a)

a    1
d    3
e    4
dtype: int64

### index series

In [79]:
q[0]

1

In [80]:
q['a']

1

In [82]:
q[0:2]

a    1
d    3
dtype: int64

In [83]:
q['a':'e']

a    1
d    3
e    4
dtype: int64

In [85]:
q[['a','e']]

a    1
e    4
dtype: int64

### manipulation series

## DataFrame

### construct dataframe

In [91]:
a=pd.DataFrame([[0,1,2],[2,3,4]],columns=['one','two','three'],index=['a','b'])


In [87]:
pd.DataFrame({'one':[0,2],'two':[1,3],'three':[2,4]})


one  two  three
0    0    1      2
1    2    3      4

In [90]:
pd.DataFrame([{'one':1,'two':2},{'one':3,'two':4}])

one  two
0    1    2
1    3    4

### index DataFrame

In [92]:
a['one']

a    0
b    2
Name: one, dtype: int64

In [93]:
a[['one','two']]

one  two
a    0    1
b    2    3

In [96]:
a[0:1]

one  two  three
a    0    1      2

In [97]:
a['a':'b']

one  two  three
a    0    1      2
b    2    3      4

In [101]:
a.loc['a','one']

0

In [102]:
a.loc['a',]

one      0
two      1
three    2
Name: a, dtype: int64

In [103]:
a.iloc[1,]

one      2
two      3
three    4
Name: b, dtype: int64

### manipulation

In [105]:
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                   'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [5, 6, 7, 8]})

In [108]:
df1.merge(df2, left_on='lkey', right_on='rkey')

lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7